### ISSUE TITLE
AttributeError: 'str' object has no attribute 'get_domain'

### ISSUE THREAD

**Issue by vmario89** [elem74/fabaccess-config-generator#6]
development branch:

Mit folgender `maschinenliste.csv` crasht der output, sobald ich in `settings.ini` den key `show_machines = True` setze

```
Name Domäne;Name Bereich;Name Unterbereich;Name Maschine;Maschinenbeschreibung;Manager Unterbereich;ID Alternativrolle;Name Alternativrolle;Wiki-URL;ID Domäne;ID Bereich;ID Unterbereich;ID Maschine;Aktor ID;Aktor Typ;Kommentar
ZAM;Central Stairs;1. Raum;1 Lampe;Eine einfache Funzel. Kann weiter nix;;;;;zam;raum1;ecke1;lamp;1;Tasmota;Demo Setup
ZAM;Central Stairs;1. Raum;2 LED Pfeil;Noch ein Leuchteteil. In Arrow-Shape;;;;;zam;raum1;ecke2;arrow;2;Tasmota;Demo Setup
ZAM;Central Stairs;1. Raum;3 Der laute Lüfter;Ein sinnfreier Aktor, der sich bemerkbar macht;;;;;zam;raum1;ecke3;fan;3;Tasmota;Demo Setup
ZAM;Central Stairs;1. Raum;4 LED Lauflicht;Blinky Shit yeah!;;;;;zam;raum1;ecke4;mesh;4;Tasmota;Demo Setup
ZAM;Central Stairs;1. Raum;5 Random Dingens #1;Utilize it as you like;;;;;zam;raum1;ecke5;random1;5;Tasmota;Demo Setup
ZAM;Central Stairs;1. Raum;6 Random Dingens #2;Utilize it as you like;;;;;zam;raum1;ecke6;random2;6;Tasmota;Demo Setup
ZAM;Central Stairs;1. Raum;7 Random Dingens #3;Utilize it as you like;;;;;zam;raum1;ecke7;random3;7;Tasmota;Demo Setup
ZAM;Central Stairs;1. Raum;8 Mac Gyver;Vorsitzender des Repair Cafe Dachverbands;;;;https://de.wikipedia.org/wiki/MacGyver;zam;raum1;ecke8;macgyver;8;mp3play;Demo Setup
ZAM;Central Stairs;1. Raum;9 Shutdown;Poweroff Raspberry Pi;;;;;zam;raum1;ecke9;shutdown;9;shutdown;Demo Setup
```

Error:

```
Traceback (most recent call last):
  File "/opt/fabinfra/fabaccess-config-generator/config-generator.py", line 38, in <module>
    display_machine(m)
  File "/opt/fabinfra/fabaccess-config-generator/generator/core.py", line 679, in display_machine
    scope = machine_object.get_domain()
            ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'get_domain'
```

**Comment by elem74** [comment]
Der development-branch beinhaltet einen Fix.

**Comment by vmario89** [comment]
das hat's gefixed! vielen Dank!
